apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose -f production.yml convert
    kompose.version: 1.17.0 (a74acad)
  creationTimestamp: null
  labels:
    io.kompose.service: caddy
  name: caddy
spec:
  ports:
  - name: "80"
    port: 80
    targetPort: 80
  - name: "443"
    port: 443
    targetPort: 443
  selector:
    io.kompose.service: caddy
status:
  loadBalancer: {}
